package main

import (
    "fmt"
    _ "github.com/asktop/gotools/acaptcha"
    _ "github.com/asktop/gotools/acast"
    _ "github.com/asktop/gotools/aclient"
    _ "github.com/asktop/gotools/acron"
    _ "github.com/asktop/gotools/aemail"
    _ "github.com/asktop/gotools/afile"
    _ "github.com/asktop/gotools/agzip"
    _ "github.com/asktop/gotools/aimage"
    _ "github.com/asktop/gotools/ajson"
    _ "github.com/asktop/gotools/ajwt"
    _ "github.com/asktop/gotools/akey"
    _ "github.com/asktop/gotools/alimit"
    _ "github.com/asktop/gotools/alist"
    _ "github.com/asktop/gotools/amap"
    _ "github.com/asktop/gotools/amath"
    _ "github.com/asktop/gotools/amsg"
    _ "github.com/asktop/gotools/aotp"
    _ "github.com/asktop/gotools/apage"
    _ "github.com/asktop/gotools/aphp"
    _ "github.com/asktop/gotools/aqrcode"
    _ "github.com/asktop/gotools/arand"
    _ "github.com/asktop/gotools/areflect"
    _ "github.com/asktop/gotools/arsa"
    _ "github.com/asktop/gotools/ascan"
    _ "github.com/asktop/gotools/aset"
    _ "github.com/asktop/gotools/asign"
    _ "github.com/asktop/gotools/aslice"
    _ "github.com/asktop/gotools/asms"
    _ "github.com/asktop/gotools/asort"
    _ "github.com/asktop/gotools/astring"
    _ "github.com/asktop/gotools/async"
    _ "github.com/asktop/gotools/atag"
    _ "github.com/asktop/gotools/atest"
    _ "github.com/asktop/gotools/atime"
    _ "github.com/asktop/gotools/aunique"
    _ "github.com/asktop/gotools/aupload"
    _ "github.com/asktop/gotools/aurl"
    _ "github.com/asktop/gotools/auuid"
    _ "github.com/asktop/gotools/avalid"
    _ "github.com/asktop/gotools/awx"
    _ "github.com/asktop/gotools/ayaml"
    _ "github.com/asktop/gotools/azlib"
    _ "github.com/asktop/gotools/cache"
    _ "github.com/asktop/gotools/db"
    _ "github.com/asktop/gotools/log"
    _ "github.com/asktop/gotools/mongo"
)

func main() {
    fmt.Println("go get github.com/asktop/gotools")
}
