// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base/net/protobuf/demo.proto

//指定编译go文件的包名

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//定义请求参数
type GetUsersIn struct {
	//用户名
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersIn) Reset()         { *m = GetUsersIn{} }
func (m *GetUsersIn) String() string { return proto.CompactTextString(m) }
func (*GetUsersIn) ProtoMessage()    {}
func (*GetUsersIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a82ba1ada857fc, []int{0}
}

func (m *GetUsersIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersIn.Unmarshal(m, b)
}
func (m *GetUsersIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersIn.Marshal(b, m, deterministic)
}
func (m *GetUsersIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersIn.Merge(m, src)
}
func (m *GetUsersIn) XXX_Size() int {
	return xxx_messageInfo_GetUsersIn.Size(m)
}
func (m *GetUsersIn) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersIn.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersIn proto.InternalMessageInfo

func (m *GetUsersIn) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

//定义响应参数
type GetUsersOut struct {
	//状态（0：失败；1：成功）
	Status int64 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	//错误类型
	Code int64 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	//错误信息
	Msg string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	//用户列表：key:用户id；value:用户名
	UserMap map[int64]string `protobuf:"bytes,4,rep,name=user_map,json=userMap,proto3" json:"user_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	//用户列表
	Users                []*User  `protobuf:"bytes,5,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersOut) Reset()         { *m = GetUsersOut{} }
func (m *GetUsersOut) String() string { return proto.CompactTextString(m) }
func (*GetUsersOut) ProtoMessage()    {}
func (*GetUsersOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a82ba1ada857fc, []int{1}
}

func (m *GetUsersOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersOut.Unmarshal(m, b)
}
func (m *GetUsersOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersOut.Marshal(b, m, deterministic)
}
func (m *GetUsersOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersOut.Merge(m, src)
}
func (m *GetUsersOut) XXX_Size() int {
	return xxx_messageInfo_GetUsersOut.Size(m)
}
func (m *GetUsersOut) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersOut.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersOut proto.InternalMessageInfo

func (m *GetUsersOut) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetUsersOut) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetUsersOut) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetUsersOut) GetUserMap() map[int64]string {
	if m != nil {
		return m.UserMap
	}
	return nil
}

func (m *GetUsersOut) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type User struct {
	//用户id
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	//用户名
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_01a82ba1ada857fc, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*GetUsersIn)(nil), "pb.GetUsersIn")
	proto.RegisterType((*GetUsersOut)(nil), "pb.GetUsersOut")
	proto.RegisterMapType((map[int64]string)(nil), "pb.GetUsersOut.UserMapEntry")
	proto.RegisterType((*User)(nil), "pb.User")
}

func init() { proto.RegisterFile("base/net/protobuf/demo.proto", fileDescriptor_01a82ba1ada857fc) }

var fileDescriptor_01a82ba1ada857fc = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0x87, 0x6d, 0xda, 0xcd, 0xee, 0x4c, 0xa6, 0x1c, 0x44, 0xca, 0x18, 0x52, 0x7a, 0x35, 0x04,
	0x5b, 0x98, 0x88, 0xb2, 0x6b, 0x45, 0x76, 0x21, 0x42, 0xc1, 0x6b, 0x49, 0xed, 0x51, 0x86, 0x36,
	0x09, 0x4d, 0x22, 0xec, 0x6d, 0x7d, 0x14, 0x49, 0xda, 0x69, 0xf1, 0xee, 0xfb, 0x85, 0xf3, 0xe5,
	0xfc, 0x81, 0x45, 0xc5, 0x35, 0x15, 0x82, 0x4c, 0xa1, 0x5a, 0x69, 0x64, 0x65, 0xdf, 0x8a, 0x9a,
	0x1a, 0x99, 0xfb, 0x84, 0x4c, 0x55, 0x59, 0x0a, 0xf0, 0x40, 0xe6, 0x59, 0x53, 0xab, 0x37, 0x02,
	0x11, 0x22, 0xc1, 0x1b, 0x4a, 0x82, 0x34, 0x58, 0x4e, 0x4a, 0xcf, 0xd9, 0x77, 0x00, 0xd3, 0x7d,
	0xc9, 0x93, 0x35, 0x78, 0x06, 0x63, 0x6d, 0xb8, 0xb1, 0xda, 0x57, 0x85, 0x65, 0x9f, 0x9c, 0xfb,
	0x2a, 0x6b, 0x4a, 0x98, 0x7f, 0xf5, 0x8c, 0x27, 0x10, 0x36, 0xfa, 0x3d, 0x09, 0xfd, 0x77, 0x0e,
	0xf1, 0x06, 0x62, 0xab, 0xa9, 0x7d, 0x69, 0xb8, 0x4a, 0xa2, 0x34, 0x5c, 0x4e, 0x57, 0x8b, 0x5c,
	0x55, 0xf9, 0xa0, 0x41, 0xee, 0xe0, 0x91, 0xab, 0x7b, 0x61, 0xda, 0x5d, 0x79, 0x68, 0xbb, 0x84,
	0xe7, 0x30, 0x72, 0xa8, 0x93, 0x91, 0xb7, 0x62, 0x67, 0xb9, 0xca, 0xb2, 0x7b, 0x9e, 0xaf, 0xe1,
	0x68, 0x28, 0xba, 0xd6, 0x1f, 0xb4, 0xeb, 0x67, 0x74, 0x88, 0xa7, 0x30, 0xfa, 0xe2, 0x9f, 0xb6,
	0x9b, 0x70, 0x52, 0x76, 0x61, 0xcd, 0x6e, 0x83, 0xec, 0x02, 0x22, 0xe7, 0xe2, 0x0c, 0xd8, 0xb6,
	0xee, 0x15, 0xb6, 0xad, 0x7f, 0xcf, 0xc1, 0xfe, 0xce, 0xb1, 0xba, 0x86, 0xe8, 0x8e, 0x1a, 0x89,
	0x97, 0x10, 0xef, 0x87, 0xc6, 0xd9, 0x70, 0x85, 0x8d, 0x98, 0x1f, 0xff, 0x5b, 0x29, 0x3b, 0xa8,
	0xc6, 0xfe, 0xe4, 0x57, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x68, 0xec, 0x03, 0xa5, 0x92, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DemoClient is the client API for Demo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DemoClient interface {
	//定义服务中的方法
	GetUsers(ctx context.Context, in *GetUsersIn, opts ...grpc.CallOption) (*GetUsersOut, error)
}

type demoClient struct {
	cc *grpc.ClientConn
}

func NewDemoClient(cc *grpc.ClientConn) DemoClient {
	return &demoClient{cc}
}

func (c *demoClient) GetUsers(ctx context.Context, in *GetUsersIn, opts ...grpc.CallOption) (*GetUsersOut, error) {
	out := new(GetUsersOut)
	err := c.cc.Invoke(ctx, "/pb.Demo/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DemoServer is the server API for Demo service.
type DemoServer interface {
	//定义服务中的方法
	GetUsers(context.Context, *GetUsersIn) (*GetUsersOut, error)
}

// UnimplementedDemoServer can be embedded to have forward compatible implementations.
type UnimplementedDemoServer struct {
}

func (*UnimplementedDemoServer) GetUsers(ctx context.Context, req *GetUsersIn) (*GetUsersOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}

func RegisterDemoServer(s *grpc.Server, srv DemoServer) {
	s.RegisterService(&_Demo_serviceDesc, srv)
}

func _Demo_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Demo/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServer).GetUsers(ctx, req.(*GetUsersIn))
	}
	return interceptor(ctx, in, info, handler)
}

var _Demo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Demo",
	HandlerType: (*DemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsers",
			Handler:    _Demo_GetUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base/net/protobuf/demo.proto",
}
